<a href="https://colab.research.google.com/github/nemuelpalomo/Linear-Algebra-58020/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra

In [18]:
import numpy as np

X = np.array([[1, 2], [4, 7]])

inverse1 = (np.linalg.inv(X))

print(inverse1)

[[-7.  2.]
 [ 4. -1.]]


In [19]:
A = np.dot(X, inverse1)

print(A)

[[1. 0.]
 [0. 1.]]


#Inverse of a 3x3 Matrix


In [20]:
matrix = np.array([[5,2,1], [3,2,7], [4,6,1]])

inversed3 = np.linalg.inv(matrix)

print(inversed3)

[[ 0.28571429 -0.02857143 -0.08571429]
 [-0.17857143 -0.00714286  0.22857143]
 [-0.07142857  0.15714286 -0.02857143]]


#Transpose of the 3x3 Matrix

In [22]:
transpose1 = np.transpose(matrix)
print(transpose1)

[[5 3 4]
 [2 2 6]
 [1 7 1]]


#Inverse of a 4x4 Matrix

In [23]:
matrix1 = np.array([[6,5,1,2],[5,1,7,2],[7,2,5,1],[8,5,9,1]])
print(matrix1)

[[6 5 1 2]
 [5 1 7 2]
 [7 2 5 1]
 [8 5 9 1]]


In [24]:
inversed = np.linalg.inv(matrix1)
print(inversed)

[[-0.01098901 -0.11355311  0.35897436 -0.10989011]
 [ 0.12087912 -0.08424908 -0.28205128  0.20879121]
 [-0.08791209  0.09157509 -0.12820513  0.12087912]
 [ 0.27472527  0.50549451 -0.30769231 -0.25274725]]


#Transpose of the 4x4 Matrix

In [25]:
transpose2 = np.transpose(matrix1)
print(transpose2)

[[6 5 7 8]
 [5 1 2 5]
 [1 7 5 9]
 [2 2 1 1]]
