<a href="https://colab.research.google.com/github/nemuelpalomo/Linear-Algebra-58020/blob/main/Determinants_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])

print(A) #Matrix A
print("")
print("")
print("")
print(np.linalg.det(A)) #Determinant of matrix A
print("")
print("")
print("")
print(round(np.linalg.det(A))) #Round up to the nearest integer



[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]



-13.999999999999996



-14
