<a href="https://colab.research.google.com/github/nemuelpalomo/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [44]:
studentC = 19

studentA = (studentC - 6)
studentB = (studentC * 3)

print("Student A has ", studentA)
print("Student B has ", studentB)
print("Student C has ", studentC)


Student A has  13
Student B has  57
Student C has  19


# Problem 2. Solve each system: (30 points)

In [55]:
import numpy as np
from scipy import linalg

A = np.array([[3,-1,1], [9,-3,3], [-12,4,-4]])
print("Matrix A:\n", A)

#The matrix is singular, we cannot somehow inverse it but we can use pinv to see the output and the results.

inv_A = np.linalg.pinv(A)
print("\nInverse of Matrix A:\n", inv_A)

B = np.array([[5],[10],[-20]])
print("\nMatrix A:\n", A)

X = np.dot(inv_A, B)
print("\nDot:\n", X)

C = np.dot(A, X)
print("\nChecking:\n", C)

Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Inverse of Matrix A:
 [[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]]

Matrix A:
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Dot:
 [[ 1.20629371]
 [-0.4020979 ]
 [ 0.4020979 ]]

Checking:
 [[  4.42307692]
 [ 13.26923077]
 [-17.69230769]]


# Problem 3. Consider the matrix. (40 points)

In [28]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print("The Matrix:\n")
print(A, "\n")
b,c = np.linalg.eig(A)

print("The eigenvalues:\n",b,"\n")
print("The eigenvectors:\n",c.round())


The Matrix:

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalues:
 [-1.  3.  2.] 

The eigenvectors:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
