<a href="https://colab.research.google.com/github/nemuelpalomo/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [17]:
#Question 1. Create a Python code that displays a square matrix whose length is 5 (10points)

A = np.eye(5)

print(A)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
#Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10points)

B = np.array([[1,1,1,1,1],[0,1,1,1,1],[0,0,1,1,1],[0,0,0,1,1],[0,0,0,0,1]])

print(B)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


In [36]:
#Question 3. Create a Python code that displays a square matrix which is symmetrical (10points)

symmetric = np.array([[1, 7, 3],[7, 4, -5],[3,-5, 6]]) #untransposed
print(symmetric)
print("")
symmetric_T = np.transpose(symmetric) #transposed which proves the matrix is symmetrical
print(symmetric_T)

[[ 1  7  3]
 [ 7  4 -5]
 [ 3 -5  6]]

[[ 1  7  3]
 [ 7  4 -5]
 [ 3 -5  6]]


In [20]:
#Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
print("")

inv_C = np.linalg.inv(C)

print(inv_C) #Inverse of matrix C

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [23]:
#Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

C = np.array([[1,2,3],[2,3,3],[3,4,-2]])

print(C) #Matrix C
print("")

det_C = np.linalg.det(C)

print(det_C) #Matrix C's determinant

print("")

print(round(np.linalg.det(C))) #Determinant rounded 


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

5.000000000000001

5


In [33]:
#Question 6. Find the roots of the linear equations by showing its python codes (30 points)

D = np.array([[5,4,1,3.4],[10,9,4,8.8],[10,13,15,19.2]]) #Given Matrix
print(D)

print("")

sqrt_D = np.sqrt(D)  #Roots of matrix D
print(sqrt_D) 

[[ 5.   4.   1.   3.4]
 [10.   9.   4.   8.8]
 [10.  13.  15.  19.2]]

[[2.23606798 2.         1.         1.84390889]
 [3.16227766 3.         2.         2.96647939]
 [3.16227766 3.60555128 3.87298335 4.38178046]]
