<a href="https://colab.research.google.com/github/nemuelpalomo/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Prelim Exam


#Question 1


In [2]:
import numpy as np

C = np.eye(4)

print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#Question 2


In [3]:
answer = 2*C

print(answer)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


##Question 3


In [4]:
A = np.array([2,7,4])
B = np.array([3,9,8])

answer2 = np.cross(A,B)

print(answer2)

[20 -4 -3]
