<a href="https://colab.research.google.com/github/nemuelpalomo/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#Matrix A

A = np.array([[1,1,1],[1,2,2],[1,2,3]]);
print("")
print(A)

inv_A = np.linalg.inv(A)
print("")
print(inv_A)

B = np.array([[5],[6],[8]]);
print("")
print(B)

X = np.dot(inv_A, B)
print("")
print(X)


[[1 1 1]
 [1 2 2]
 [1 2 3]]

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]

[[5]
 [6]
 [8]]

[[ 4.]
 [-1.]
 [ 2.]]
