<a href="https://colab.research.google.com/github/nemuelpalomo/Linear-Algebra-58020/blob/main/Python%20Exercise%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [1]:
import numpy as np
#This creates a 1x3 matrix.

r = np.array([8,8,5])
print(r)

[8 8 5]


In [2]:
#Sum of Matrix A and B

a = np.array([[-5, 0],[4, 1]])
b = np.array([[6, -3],[2, 3]])

print(a + b)


[[ 1 -3]
 [ 6  4]]


In [3]:
#Difference 1 of A and B: A - B

a = np.array([[-5, 0],[4, 1]])
b = np.array([[6, -3],[2, 3]])

print(a - b)

[[-11   3]
 [  2  -2]]


In [4]:
#Difference 2 of A and B: B - B

b = np.array([[6, -3],[2, 3]])

print(b - b)

[[0 0]
 [0 0]]
